name: Build and Release Android

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    name: Build APK and Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Generate Release Name
        id: release_name
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "release_name=Release ${{ github.ref_name }}" >> $GITHUB_OUTPUT
            echo "release_tag=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          elif [[ $GITHUB_REF == refs/heads/main ]]; then
            COMMIT_SHA="${GITHUB_SHA:0:7}"
            CURRENT_DATE=$(date +'%Y-%m-%d-%H-%M')
            echo "release_name=Build from main branch ($CURRENT_DATE)" >> $GITHUB_OUTPUT
            echo "release_tag=build-$CURRENT_DATE-$COMMIT_SHA" >> $GITHUB_OUTPUT
          else
            PR_NUMBER=$(echo $GITHUB_REF | sed -n 's/refs\/pull\/\([0-9]*\)\/merge/\1/p')
            echo "release_name=Pull Request #$PR_NUMBER" >> $GITHUB_OUTPUT
            echo "release_tag=pr-$PR_NUMBER" >> $GITHUB_OUTPUT
          fi

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
          draft: false
          prerelease: ${{ github.ref != 'refs/heads/main' && !startsWith(github.ref, 'refs/tags/') }}
          name: ${{ steps.release_name.outputs.release_name }}
          tag_name: ${{ steps.release_name.outputs.release_tag }}
          body: |
            Build created on ${{ github.event.repository.updated_at }}
            
            - Commit: ${{ github.sha }}
            - Actor: ${{ github.actor }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
